FROM gcr.io/organic-storm-201412/fetch-ledger-develop:latest

RUN sudo apt-get update && \
    sudo apt-get upgrade -y && \
    sudo apt-get install -y python && \
    sudo apt-get install -y python-pip && \
    sudo apt-get install -y python3 && \
    sudo apt-get install -y python3-pip

WORKDIR /build

ENTRYPOINT []