sequenceDiagram
        Agent ->> Agent: search_services()
        activate Agent
        Agent ->> OEF Node: (search_id, query)
        deactivate Agent
        activate OEF Node
        Agent ->> Agent: run()
        activate Agent
        OEF Node ->> Agent: (search_id, List[agent_ids])
        deactivate OEF Node
        activate Agent
        note left of Agent: on_search_result() called
        deactivate Agent
        deactivate Agent